version: "3"
services:
  web:
    image: httpd
    ports:
      - "80:80"
    # links:
    #   - fluentd
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: httpd.access
  # fluentd:
  #   build: ./fluentd
  #   volumes:
  #     - ./fluentd/conf:/fluentd/etc
  #   links:
  #     - "localstack"
  #   ports:
  #     - "24224:24224"
  #     - "24224:24224/udp"
  localstack:
    image: localstack/localstack:1.3.1
    container_name: "localstack"
    ports:
      - 4566:4566
      - 8000:8000
    volumes:
      - ./localstack:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
      - 'localstack-data:/tmp/localstack'
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DISABLE_CORS_CHECKS=1

volumes:
  localstack-data:
    driver: 'local'
